# docker compose --file compose.linux.yml up --build
services:

  tiny-gordon:
    build: 
      context: .
      dockerfile: Dockerfile

    ports:
      - 8000:8000
    environment:
      - DMR_BASE_URL=${DMR_BASE_URL}
      - MODEL_RUNNER_MODEL=${MODEL_RUNNER_MODEL}
      - MODEL_RUNNER_EMBEDDING_MODEL=${MODEL_RUNNER_EMBEDDING_MODEL}
    command: ["adk", "web", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - download-model
      - download-embedding-model

  tiny-gordon-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:8000
    environment:
      - DMR_BASE_URL=${DMR_BASE_URL}
      - MODEL_RUNNER_MODEL=${MODEL_RUNNER_MODEL}
      - MODEL_RUNNER_EMBEDDING_MODEL=${MODEL_RUNNER_EMBEDDING_MODEL}
    command: ["adk", "api_server", "--host", "0.0.0.0", "--port", "8000"]
    depends_on:
      - download-model
      - download-embedding-model

  download-model:
    image: curlimages/curl:8.12.1
    entrypoint: |
      sh -c '
      # Download Chat model
      curl -s "${DMR_BASE_URL}/models/create" -d @- << EOF
      {"from": "${MODEL_RUNNER_MODEL}"}
      EOF
      '

  download-embedding-model:
    image: curlimages/curl:8.12.1
    entrypoint: |
      sh -c '
      # Download Chat model
      curl -s "${DMR_BASE_URL}/models/create" -d @- << EOF
      {"from": "${MODEL_RUNNER_EMBEDDING_MODEL}"}
      EOF
      '