# docker compose up --build
services:

  tiny-gordon:
    build: 
      context: .
      dockerfile: Dockerfile

    ports:
      - 8000:8000
    environment:
      - DMR_BASE_URL=${DMR_BASE_URL}
      - MODEL_RUNNER_MODEL=${MODEL_RUNNER_MODEL}
      - MODEL_RUNNER_EMBEDDING_MODEL=${MODEL_RUNNER_EMBEDDING_MODEL}
    command: ["adk", "web", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - download-model
      - download-embedding-model

  tiny-gordon-api:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - 9000:8000
    environment:
      - DMR_BASE_URL=${DMR_BASE_URL}
      - MODEL_RUNNER_MODEL=${MODEL_RUNNER_MODEL}
      - MODEL_RUNNER_EMBEDDING_MODEL=${MODEL_RUNNER_EMBEDDING_MODEL}
    command: ["adk", "api_server", "--host", "0.0.0.0", "--port", "8000"]
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - download-model
      - download-embedding-model


  download-model:
    provider:
      type: model
      options:
        model: ${MODEL_RUNNER_MODEL}

  download-embedding-model:
    provider:
      type: model
      options:
        model: ${MODEL_RUNNER_EMBEDDING_MODEL}

  redis-server:
    image: redis:8.0.0-alpine3.21
    environment: 
      - REDIS_ARGS=--save 30 1
      # snapshot
    ports:
      - 6379:6379
    volumes:
      - ./data:/data
      #- ${LOCAL_WORKSPACE_FOLDER}/data:/data

  data-loader:
    profiles: ["init"]
    build: 
      context: ./data-loader
      dockerfile: Dockerfile
    environment:
      - DMR_BASE_URL=${DMR_BASE_URL}
      - MODEL_RUNNER_EMBEDDING_MODEL=${MODEL_RUNNER_EMBEDDING_MODEL}
    depends_on:
      - download-embedding-model-for-data-loader

  download-embedding-model-for-data-loader:
    profiles: ["init"]
    provider:
      type: model
      options:
        model: ${MODEL_RUNNER_EMBEDDING_MODEL}